// AUTO-GENERATED BY VN-SUTRA COMPILER
export default [
    {
        "type": "scene.transition",
        "transitionType": "fade",
        "color": "#000000",
        "duration": 250
    },
    {
        "type": "background",
        "reset": true,
        "asset": "futon_room"
    },
    {
        "type": "actor.reset",
        "actor": "mary",
        "fields": [
            "scale"
        ]
    },
    {
        "type": "sprite.apply",
        "actor": "mary",
        "sprite": "casualSmile",
        "options": {
            "duration": 0
        },
        "fallback": {
            "outfit": "Casual",
            "mood": "Rin_Casual_Smile"
        }
    },
    {
        "type": "actor.set",
        "actor": "mary",
        "props": {
            "x": -0.25,
            "y": {
                "portrait": 0.1,
                "android": 0.2,
                "default": 0.1
            }
        }
    },
    {
        "type": "actor.call",
        "actor": "mary",
        "method": "slideIn",
        "args": [
            0.48,
            0.8
        ]
    },
    {
        "type": "storage.get",
        "key": "name",
        "var": "playerName"
    },
    {
        "type": "storage.get",
        "key": "demo-tour-focus",
        "var": "tourFocus"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene3.return"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene3.named",
        "params": {
            "name": {
                "fromVar": "playerName"
            }
        }
    },
    {
        "type": "if",
        "test": {
            "left": {
                "fromVar": "tourFocus"
            },
            "op": "===",
            "right": "Characters"
        },
        "then": [
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene3.characters"
            }
        ],
        "else": [
            {
                "type": "if",
                "test": {
                    "left": {
                        "fromVar": "tourFocus"
                    },
                    "op": "===",
                    "right": "Visual effects"
                },
                "then": [
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene3.effects"
                    }
                ],
                "else": [
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene3.flow"
                    }
                ]
            }
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene3.recap"
    },
    {
        "type": "choice",
        "var": "demoHighlights",
        "message": "@scene3.multiChoicePrompt",
        "options": [
            "Character design",
            "UI clarity",
            "Story flow"
        ],
        "multiSelect": true
    },
    {
        "type": "storage.set",
        "key": "demo-highlights",
        "value": {
            "fromVar": "demoHighlights"
        }
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene3.multiChoiceSummary",
        "params": {
            "choices": {
                "fromVar": "demoHighlights"
            }
        }
    },
    {
        "type": "choice",
        "var": "nextStep",
        "message": "@scene3.nextStepPrompt",
        "options": [
            "Open the docs",
            "Browse chapters",
            "Replay the demo"
        ],
        "optionsI18nKey": "scene3.nextStepOptions"
    },
    {
        "type": "if",
        "test": {
            "left": {
                "fromVar": "nextStep"
            },
            "op": "===",
            "right": "Open the docs"
        },
        "then": [
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene3.nextDocs"
            }
        ],
        "else": [
            {
                "type": "if",
                "test": {
                    "left": {
                        "fromVar": "nextStep"
                    },
                    "op": "===",
                    "right": "Browse chapters"
                },
                "then": [
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene3.nextChapters"
                    }
                ],
                "else": [
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene3.nextReplay"
                    }
                ]
            }
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene3.final"
    },
    {
        "type": "actor.call",
        "actor": "mary",
        "method": "slideOut"
    },
    {
        "type": "achievement",
        "id": "story.chapter-complete",
        "amount": 1
    },
    {
        "type": "end"
    }
];
