// AUTO-GENERATED BY VN-SUTRA COMPILER
export default [
    {
        "type": "scene.transition",
        "transitionType": "fade",
        "color": "#111111",
        "duration": 250
    },
    {
        "type": "background",
        "reset": true,
        "asset": "apartment_ext"
    },
    {
        "type": "actor.reset",
        "actor": "mary",
        "fields": [
            "scale",
            "y"
        ]
    },
    {
        "type": "sprite.apply",
        "actor": "mary",
        "sprite": "casualOpenSmile",
        "options": {
            "duration": 0
        }
    },
    {
        "type": "actor.set",
        "actor": "mary",
        "props": {
            "x": 0.5
        }
    },
    {
        "type": "actor.show",
        "actor": "mary"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene2.makeScenes"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene2.addAssets"
    },
    {
        "type": "parallel",
        "sequences": [
            [
                {
                    "type": "effect.screen-shake",
                    "intensity": 3,
                    "duration": 180
                }
            ],
            [
                {
                    "type": "wait",
                    "duration": 120
                },
                {
                    "type": "actor.call",
                    "actor": "mary",
                    "method": "slideIn",
                    "args": [
                        0.48,
                        0.2
                    ]
                }
            ]
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene2.movement"
    },
    {
        "type": "choice",
        "var": "tourFocus",
        "message": "@scene2.question",
        "options": [
            "Characters",
            "Visual effects",
            "Story flow"
        ],
        "optionsI18nKey": "scene2.tourOptions"
    },
    {
        "type": "storage.set",
        "key": "demo-tour-focus",
        "value": {
            "fromVar": "tourFocus"
        }
    },
    {
        "type": "if",
        "test": {
            "left": {
                "fromVar": "tourFocus"
            },
            "op": "===",
            "right": "Characters"
        },
        "then": [
            {
                "type": "sprite.apply",
                "actor": "mary",
                "sprite": "casualEyesClosed"
            },
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene2.characters"
            },
            {
                "type": "sprite.apply",
                "actor": "mary",
                "sprite": "casualOpenSmile"
            },
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene2.charactersFollowup"
            }
        ],
        "else": [
            {
                "type": "if",
                "test": {
                    "left": {
                        "fromVar": "tourFocus"
                    },
                    "op": "===",
                    "right": "Visual effects"
                },
                "then": [
                    {
                        "type": "actor.prop",
                        "actor": "mary",
                        "prop": "grayscale",
                        "value": true
                    },
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.grayscale"
                    },
                    {
                        "type": "background.prop",
                        "prop": "grayscale",
                        "value": true
                    },
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.bgGrayscale"
                    },
                    {
                        "type": "actor.prop",
                        "actor": "mary",
                        "prop": "grayscale",
                        "value": false
                    },
                    {
                        "type": "background.prop",
                        "prop": "grayscale",
                        "value": false
                    },
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.grayscaleReset"
                    },
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.bgGrayscaleReset"
                    }
                ],
                "else": [
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.explanation"
                    },
                    {
                        "type": "dialog",
                        "actor": "mary",
                        "text": "@scene2.docs"
                    }
                ]
            }
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene2.goodbye"
    },
    {
        "type": "actor.call",
        "actor": "mary",
        "method": "slideOut"
    },
    {
        "type": "effect.flash",
        "color": "#f8f8ff",
        "duration": 140
    },
    {
        "type": "jump",
        "scene": "scene3"
    }
];
