// AUTO-GENERATED BY VN-SUTRA COMPILER
export default [
    {
        "type": "scene.transition",
        "transitionType": "fade",
        "color": "#000000",
        "duration": 250
    },
    {
        "type": "background",
        "reset": true,
        "asset": "futon_room"
    },
    {
        "type": "actor.reset",
        "actor": "mary",
        "fields": [
            "scale"
        ]
    },
    {
        "type": "sprite.apply",
        "actor": "mary",
        "sprite": "casualSmile"
    },
    {
        "type": "actor.set",
        "actor": "mary",
        "props": {
            "x": -0.25,
            "y": {
                "portrait": 0.1,
                "android": 0.2,
                "default": -0.4
            }
        }
    },
    {
        "type": "actor.call",
        "actor": "mary",
        "method": "slideIn",
        "args": [
            0.5,
            1
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.hello"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.intro"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.introduction"
    },
    {
        "type": "input",
        "var": "name",
        "message": "@scene1.namePrompt",
        "placeholder": "@scene1.defaultName",
        "trim": true
    },
    {
        "type": "storage.set",
        "key": "name",
        "value": {
            "fromVar": "name"
        }
    },
    {
        "type": "if",
        "test": {
            "left": {
                "fromVar": "name"
            },
            "op": "===",
            "right": "Peanut"
        },
        "then": [
            {
                "type": "sprite.apply",
                "actor": "mary",
                "sprite": "casualEyesClosed"
            },
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene1.correctGuess"
            }
        ],
        "else": [
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene1.wrongGuess",
                "params": {
                    "name": {
                        "fromVar": "name"
                    }
                }
            }
        ]
    },
    {
        "type": "sprite.apply",
        "actor": "mary",
        "sprite": "casualOpenSmile"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.maryIntro"
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.question"
    },
    {
        "type": "choice",
        "var": "que1",
        "message": "What do you think is VN-Sutra?",
        "options": [
            "Cookie",
            "SDK for Visual Novels"
        ],
        "optionsI18nKey": "scene1.answerOptions",
        "firstOptionVar": "firstAnswer"
    },
    {
        "type": "if",
        "test": {
            "left": {
                "fromVar": "que1"
            },
            "op": "===",
            "right": "$firstAnswer"
        },
        "then": [
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene1.wrongAnswer"
            }
        ],
        "else": [
            {
                "type": "dialog",
                "actor": "mary",
                "text": "@scene1.rightAnswer"
            }
        ]
    },
    {
        "type": "dialog",
        "actor": "mary",
        "text": "@scene1.question2"
    },
    {
        "type": "effect.flash",
        "color": "#ffffff",
        "duration": 120
    },
    {
        "type": "jump",
        "scene": "scene2"
    }
];
